import turtle
import time


def climbing(siz, col):
    turtle.clear()
    turtle.shape('turtle')
    turtle.pensize(siz)
    turtle.pencolor(col)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.write("Hurray! Made it to the top!", font=('Times New Roman', 16, 'bold'), align='center')
    time.sleep(1)

def swimming(siz, col):
    turtle.clear()
    turtle.shape('turtle')
    fill_color = str("blue")
    turtle.penup()
    turtle.goto(-250, 250)
    turtle.pendown()
    turtle.pensize(siz)
    turtle.pencolor(col)
    turtle.fillcolor(fill_color)
    turtle.begin_fill()
    turtle.circle(50)
    turtle.end_fill()
    turtle.fillcolor('green')
    turtle.pencolor('brown')
    turtle.circle(60)
    turtle.left(90)
    turtle.forward(30)
    turtle.write("Yeah! I’m swimming!", font=('Times New Roman', 16, 'bold'), align='center')
    time.sleep(1)

def eating():
    turtle.clear()
    colors = ["red", "blue", "yellow", "orange"]
    turtle.shape('turtle')
    turtle.penup()
    turtle.goto(-250, -250)
    turtle.pendown()
    hor = int(-250)
    vrt = int(-250)
    for x in range(0,4):
        hor = hor + 10
        vrt = vrt + 10
        turtle.pencolor(colors[x])
        turtle.penup()
        turtle.goto(hor, vrt)
        turtle.pendown()
        turtle.begin_fill()
        turtle.circle(4)
        turtle.end_fill()
        turtle.pencolor('white')
        turtle.begin_fill()
        turtle.circle(4)
        turtle.end_fill()
        time.sleep(0.5)
    turtle.pencolor('black')
    turtle.write("Wow! What a great meal!", font=('Times New Roman', 16, 'bold'), align='center')
    time.sleep(1)

def sleeping():
    turtle.clear()
    turtle.shape('turtle')
    turtle.penup()
    turtle.goto(250, -250)
    turtle.pendown()
    turtle.pencolor('brown')
    turtle.fillcolor('brown')
    turtle.begin_fill()
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.end_fill()
    turtle.pencolor('brown')
    turtle.fillcolor('white')
    turtle.forward(37)
    turtle.left(90)
    turtle.forward(60)
    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(37)
    turtle.right(90)
    turtle.forward(37)
    turtle.right(90)
    turtle.forward(37)
    turtle.end_fill()
    turtle.pencolor('green')
    turtle.fillcolor('green')
    turtle.write("Good Night!", font=('Times New Roman', 16, 'bold'), align='center')
    time.sleep(1)


def main():
    turtle.setup(1200, 1000)
    pen_size = int(5)
    colour = str("blue")
    climbing(pen_size, colour)
    swimming(pen_size, colour)
    eating()
    sleeping()
    
main()